sudo: false
language: scala
matrix:
  include:
  - env: CMD="mill __.jvm[2.11.12].test"
    jdk: oraclejdk8

  - env: CMD="mill __.jvm[2.12.7].test"
    jdk: oraclejdk9

  - env: CMD="mill __.jvm[2.13.0-M5].test"
    jdk: openjdk10

  - env: CMD="mill __.js[2.11.12].test"
    jdk: oraclejdk9

  - env: CMD="mill __.js[2.12.7].test"
    jdk: openjdk10

  - env: CMD="mill __.js[2.13.0-M5].test"
    jdk: openjdk10

  - env: CMD="mill __.native[2.11.12].test"
    jdk: openjdk10
    before_install:
    - sudo apt-get update
    - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x

  - env: CMD="mill all demo.fastOpt perftests.__.compile"
    jdk: openjdk10

  - env: CMD="sbt readme/run"
    jdk: oraclejdk8

script:
- curl -L -o ~/bin/mill https://github.com/lihaoyi/mill/releases/download/0.2.7/0.2.7 && chmod +x ~/bin/mill
- $CMD
